version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: inventarios_db
    restart: always
    environment:
      MYSQL_DATABASE: inventario_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      # Exponemos el puerto 3307 en tu PC hacia el 3306 del contenedor para evitar chocar con tu MySQL local
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: inventarios_api
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Sobrescribimos el host "localhost" por el nombre del contenedor de la base de datos "db"
      - DB_URL=jdbc:mysql://db:3306/inventario_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      - DB_USERNAME=root
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:
